services:
  frpc:
    image: ${FRPC_IMAGE:-snowdreamtech/frpc:alpine}
    command: ["-c", "/etc/frp/frpc.toml"]
    depends_on:
      - frpc-ui
    volumes:
      - ./data/frpc.generated.toml:/etc/frp/frpc.toml
    network_mode: host
    restart: always

  frpc-ui:
    image: ${FRPC_UI_IMAGE:-lahiru98s/frpc-ui:latest}
    environment:
      - PORT=4000
      - FRPC_EXEC_PATH=/usr/local/bin/frpc
    volumes:
      - ./data:/app/data
    ports:
      - "4000:4000"
    restart: unless-stopped
